using Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL
{
    public class DataBaseContext:DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Order> Orders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"server=.;initial catalog=EfTest;integrated security=true;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .Property(u => u.Id)
                .ValueGeneratedNever();// ID force generated by client

            modelBuilder.Entity<User>()
                .Property(u => u.Id)
                .UseIdentityColumn(100, 2); // تنظیمات برای ای دی 

            modelBuilder.Entity<User>()
                .Property(u => u.Score)
                .HasDefaultValue(40);//تعریف مقدار پیش فرض

            modelBuilder.Entity<User>()
                .Property(u => u.InsertDate)
                .HasDefaultValueSql("getdate()"); //استفاده از دستورات دیتابیسی و توابع و امکانات دیتابیس

            modelBuilder.Entity<Order>()
                .Property(o => o.OrderNumber)
                .HasComputedColumnSql("'MVA-'+ CAST( Year(getdate()) AS varchar) + '-' + CAST(Month(getdate()) AS varchar) + '-' + CAST([Id] AS varchar)"); //برای ایجاد فیلدهای محاسباتی سمت دیتابیس

            modelBuilder.Entity<User>()
                .Property(u => u.FullName)
                .HasComputedColumnSql("[FirstName] +'-'+ [LastName]");// نمونه ای دیگر از فیلدهای محاسباتی
        }
    }
}
